[supabase]
SUPABASE_URL="https://pgohyzmppgpeocvzfnhd.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnb2h5em1wcGdwZW9jdnpmbmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0Nzk3NTYsImV4cCI6MjA1ODA1NTc1Nn0.beT_ENV4ej3jrtSZMarq8P64eYPibvykWV96quPemw8"